### ISSUE TITLE
Please answer

### ISSUE THREAD

**Issue by IamUncas** [Ayush-Deep/Blitz-Server-Script#2]
How to use the coin system?

**Comment by Ayush-Deep** [comment]
Go To Settings
Enable Coin Sys

Write You Questions And Answers In The QuestionsList In Settings.py

**Comment by IamUncas** [comment]
I've tried it...and all the questions work...but all the questions can't be answered and don't get the ticket server

**Comment by Ayush-Deep** [comment]
You Don't Get Tickets On Answering?? Use My BsUi

**Comment by IamUncas** [comment]
how can i get your bsUi script?

**Comment by Ayush-Deep** [comment]
I already hv bsUi in my script use it
